version: '2'
services:
   kitidp-theme:
     image: kvalitetsit/simpleidp-theme:latest
   citizen-simpleidp:
     image: kitdocker.kvalitetsit.dk/kvalitetsit/simpleidp:216dc29366c81841266ee8ea7b44133d69bb10f9
     entrypoint: bash -c " ln -nsf /kitmodule /var/simplesamlphp/modules/kitmodule; /entrypoint.sh"
     depends_on:
      - kitidp-theme
     volumes_from:
      - kitidp-theme
     volumes:
      - ./citizenidp/cert:/cert
      - ./citizenidp/citizenidp-metadata:/metadata
      - ./citizenidp/userdb:/userdb
     environment:
      - IDP_CERTIFICATE=certificate.crt
      - IDP_PRIVATE_KEY=certificate.pem
      - IDP_ADMIN_PASSWORD=test123
      - IDP_TECHNICAL_EMAIL=eva@kvalitetsit.dk
      - IDP_SECRET_SALT=abcd23poiu
      - IDP_HOSTNAME=localhost:8090
      - IDP_CONTEXTPATH=citizenidp
      - IDP_PROTOCOL=http
      - IDP_THEME=kitmodule:kittheme
     ports:
      - "8090:80"
   citizen-consentidp:
     image: kvalitetsit/consent-idp:latest
     entrypoint: bash -c " ln -nsf /kitmodule /var/simplesamlphp/modules/kitmodule; /entrypoint.sh"
     depends_on:
      - kitidp-theme
     volumes_from:
      - kitidp-theme
     volumes:
      - ./consentidp/cert:/cert
      - ./consentidp/consentidp-metadata:/metadata
     environment:
      - IDP_CERTIFICATE=certificate.crt
      - IDP_PRIVATE_KEY=certificate.pem
      - IDP_ADMIN_PASSWORD=test123
      - IDP_TECHNICAL_EMAIL=eva@kvalitetsit.dk
      - IDP_SECRET_SALT=abcd23poiu
      - IDP_HOSTNAME=localhost:8092
      - IDP_CONTEXTPATH=consentidp
      - IDP_PROTOCOL=http
      - SOURCE_IDP_URL=http://localhost:8090/citizenidp/saml2/idp/metadata.php
      - CONSENT_SERVICE_URL=http://consentservice/api/consent
      - USER_ID_ATTR=urn:dk:gov:saml:cprNumberIdentification
      - IDP_THEME=kitmodule:kittheme
     ports:
      - "8092:80"
   consentservice:
     image: kvalitetsit/consent-service:latest
     environment:
      - DB_DRIVER=com.mysql.jdbc.Driver
      - DB_PASSWORD=consent1234
      - DB_USERNAME=consent
      - DB_URL=jdbc:mysql://mysqldb:3306/consent
      - NOTIFICATION_SERVICE_URL=http://jsontomqservice:8090/notificationservice
   mongo:
     image: mongo:3.3
   app-a-saml-sp:
     image: kitdocker.kvalitetsit.dk/kvalitetsit/serviceprovider-spapp:efdd0ca4ca9723ebf0d97316b047e306b597b1f0
     volumes:
      - ./appa/config:/certificates
     environment:
      - IDP_METADATA_URL=http://citizen-consentidp/consentidp/saml2/idp/metadata.php
      - IDP_LOGIN_URL=http://localhost:8092/consentidp/saml2/idp/SSOService.php  
      - CERTIFICATE=/certificates/appa.cert
      - KEY=/certificates/appa.pem
      - SP_ENTITY_ID=dev:kit:appa
      - SAML_LB_SCHEME=http
      - SAML_LB_SERVERNAME=localhost
      - SAML_LB_SERVERPORT=8082
      - APP_CONTEXT=appa
      - MONGODB=mongo
      - MONGODB_DATABASE=mongo_appa
   app-a:
     image: kitdocker.kvalitetsit.dk/kvalitetsit/serviceprovider-spviewer:efdd0ca4ca9723ebf0d97316b047e306b597b1f0
     environment:
      - PROXY_HOST=app-a-sp-proxy
   app-a-sp-proxy:
     image: kitdocker.kvalitetsit.dk/kvalitetsit/serviceprovider-spproxy:efdd0ca4ca9723ebf0d97316b047e306b597b1f0
     environment:
      - ENDPOINT_URL=http://app-a:8080/
      - SAML_URL=http://app-a-saml-sp:8080/
      - CONTEXT=appa
      - MONGODB=mongo
      - MONGODB_DATABASE=mongo_appa
      - CORRELATION_ID=correlation-id
     ports:
      - "8082:80"
   app-b-saml-sp:
     image: kitdocker.kvalitetsit.dk/kvalitetsit/serviceprovider-spapp:efdd0ca4ca9723ebf0d97316b047e306b597b1f0
     volumes:
      - ./appb/config:/certificates
     environment:
      - IDP_METADATA_URL=http://citizen-consentidp/consentidp/saml2/idp/metadata.php
      - IDP_LOGIN_URL=http://localhost:8092/consentidp/saml2/idp/SSOService.php
      - CERTIFICATE=/certificates/appb.cert
      - KEY=/certificates/appb.pem
      - SP_ENTITY_ID=dev:kit:appb
      - SAML_LB_SCHEME=http
      - SAML_LB_SERVERNAME=localhost
      - SAML_LB_SERVERPORT=8084
      - APP_CONTEXT=appb
      - MONGODB=mongo
      - MONGODB_DATABASE=mongo_appb
   app-b:
     image: kitdocker.kvalitetsit.dk/kvalitetsit/serviceprovider-spviewer:efdd0ca4ca9723ebf0d97316b047e306b597b1f0
     environment:
      - PROXY_HOST=app-b-sp-proxy
   app-b-sp-proxy:
     image: kitdocker.kvalitetsit.dk/kvalitetsit/serviceprovider-spproxy:efdd0ca4ca9723ebf0d97316b047e306b597b1f0
     environment:
      - ENDPOINT_URL=http://app-b:8080/
      - SAML_URL=http://app-b-saml-sp:8080/
      - CONTEXT=appb
      - MONGODB=mongo
      - MONGODB_DATABASE=mongo_appb
      - CORRELATION_ID=correlation-id
     ports:
      - "8084:80"
   mysqldb:
    image: mysql/mysql-server:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=my-secret-pw
      - MYSQL_DATABASE=consent
      - MYSQL_USER=consent
      - MYSQL_PASSWORD=consent1234
    ports: 
      - "3306:3306"
   rabbitmq:
    build: rabbitmq
    image: kihdev/rabbitmq
    environment:
      - RABBITMQ_DEFAULT_VHOST=/
    ports: 
      - "15672:15672"
   jsontomqservice:
    image: kitdocker.kvalitetsit.dk/kvalitetsit/jsontomqservice:325c78518d984762bc714d76e28648b1e1f0c944
    environment:
      - PORT=8090
      - MQ_URL=amqp://guest:guest@rabbitmq:5672/
      - CORRELATION_ID_HEADER_NAME=correlation-id
      - MAPPING=/notificationservice/sendNotification=iti42.exchange
    links:
      - rabbitmq
