version: '2'
services:
   citizen-simpleidp:
     image: kitdocker.kvalitetsit.dk/kvalitetsit/simpleidp:f8db175484b169ddfb0444450f89e1b498cea3ba
     volumes:
      - ./citizenidp/cert:/cert
      - ./citizenidp/citizenidp-metadata:/metadata
      - ./citizenidp/userdb:/userdb
     environment:
      - IDP_CERTIFICATE=certificate.crt
      - IDP_PRIVATE_KEY=certificate.pem
      - IDP_ADMIN_PASSWORD=test123
      - IDP_TECHNICAL_EMAIL=eva@kvalitetsit.dk
      - IDP_SECRET_SALT=abcd23poiu
      - IDP_HOSTNAME=frontend
      - IDP_CONTEXTPATH=citizenidp
      - IDP_PROTOCOL=http
     ports:
      - "80:80"
   mongo:
     image: mongo:3.3
   app-a-saml-sp:
     image: kitdocker.kvalitetsit.dk/kvalitetsit/serviceprovider-spapp:59eb03a2e9bfedfd4faa4eb70265efc25e61d3e4
     extra_hosts:
      - "frontend:172.17.0.1" 
     volumes:
      - ./appa/config:/certificates
     environment:
      - IDP_METADATA_URL=http://frontend/citizenidp/saml2/idp/metadata.php
      - IDP_LOGIN_URL=http://frontend/citizenidp/saml2/idp/SSOService.php  
      - SP_IMPORT_KEYSTORE=appa.p12
      - SP_IMPORT_PASSWORD=Test1234
      - SP_IMPORT_ALIAS=appa
      - SP_ENTITY_ID=dev:kit:appa
      - SAML_LB_SCHEME=http
      - SAML_LB_SERVERNAME=frontend
      - SAML_LB_SERVERPORT=8082
      - APP_CONTEXT=appa
      - MONGODB=mongo
      - MONGODB_DATABASE=mongo_appa
   app-a:
     image: nginx:1.11.12-alpine
     volumes:
      - ./appa/html:/usr/share/nginx/html/appa:ro
   app-a-sp-proxy:
     image: kitdocker.kvalitetsit.dk/kvalitetsit/serviceprovider-spproxy:59eb03a2e9bfedfd4faa4eb70265efc25e61d3e4
     environment:
      - ENDPOINT_URL=http://app-a/
      - SAML_URL=http://app-a-saml-sp:8080/
      - CONTEXT=appa
      - MONGODB=mongo
      - MONGODB_DATABASE=mongo_appa
      - CORRELATION_ID=correlation-id
     links:
      - app-a-saml-sp
      - mongo
      - app-a
     ports:
      - "8082:80"
