version: '2'
services:
   citizen-simpleidp:
     image: kitdocker.kvalitetsit.dk/kvalitetsit/simpleidp:f8db175484b169ddfb0444450f89e1b498cea3ba
     volumes:
      - ./citizenidp/cert:/cert
      - ./citizenidp/citizenidp-metadata:/metadata
      - ./citizenidp/userdb:/userdb
     environment:
      - IDP_CERTIFICATE=certificate.crt
      - IDP_PRIVATE_KEY=certificate.pem
      - IDP_ADMIN_PASSWORD=test123
      - IDP_TECHNICAL_EMAIL=eva@kvalitetsit.dk
      - IDP_SECRET_SALT=abcd23poiu
      - IDP_HOSTNAME=localhost:8090
      - IDP_CONTEXTPATH=citizenidp
      - IDP_PROTOCOL=http
     ports:
      - "8090:80"
   citizen-consentidp:
     image: kvalitetsit/consent-idp:latest
     volumes:
      - ./consentidp/cert:/cert
      - ./consentidp/consentidp-metadata:/metadata
     environment:
      - IDP_CERTIFICATE=certificate.crt
      - IDP_PRIVATE_KEY=certificate.pem
      - IDP_ADMIN_PASSWORD=test123
      - IDP_TECHNICAL_EMAIL=eva@kvalitetsit.dk
      - IDP_SECRET_SALT=abcd23poiu
      - IDP_HOSTNAME=localhost:8092
      - IDP_CONTEXTPATH=consentidp
      - IDP_PROTOCOL=http
      - SOURCE_IDP_URL=http://localhost:8090/citizenidp/saml2/idp/metadata.php
      - CONSENT_SERVICE_URL=http://consentservice/api/consent
      - USER_ID_ATTR=urn:dk:gov:saml:cprNumberIdentification
     ports:
      - "8092:80"
   consentservice:
     image: kvalitetsit/consent-service:latest
   mongo:
     image: mongo:3.3
   app-a-saml-sp:
     image: kitdocker.kvalitetsit.dk/kvalitetsit/serviceprovider-spapp:714fed014be5d092bf64b6a4f8639b4b23833b99
     volumes:
      - ./appa/config:/certificates
     environment:
      - IDP_METADATA_URL=http://citizen-consentidp/consentidp/saml2/idp/metadata.php
      - IDP_LOGIN_URL=http://localhost:8092/consentidp/saml2/idp/SSOService.php  
      - CERTIFICATE=/certificates/appa.cert
      - KEY=/certificates/appa.pem
      - SP_ENTITY_ID=dev:kit:appa
      - SAML_LB_SCHEME=http
      - SAML_LB_SERVERNAME=localhost
      - SAML_LB_SERVERPORT=8082
      - APP_CONTEXT=appa
      - MONGODB=mongo
      - MONGODB_DATABASE=mongo_appa
   app-a:
     image: kitdocker.kvalitetsit.dk/kvalitetsit/serviceprovider-spviewer:714fed014be5d092bf64b6a4f8639b4b23833b99
     environment:
      - PROXY_HOST=app-a-sp-proxy
   app-a-sp-proxy:
     image: kitdocker.kvalitetsit.dk/kvalitetsit/serviceprovider-spproxy:714fed014be5d092bf64b6a4f8639b4b23833b99
     environment:
      - ENDPOINT_URL=http://app-a:8080/
      - SAML_URL=http://app-a-saml-sp:8080/
      - CONTEXT=appa
      - MONGODB=mongo
      - MONGODB_DATABASE=mongo_appa
      - CORRELATION_ID=correlation-id
     ports:
      - "8082:80"
   app-b-saml-sp:
     image: kitdocker.kvalitetsit.dk/kvalitetsit/serviceprovider-spapp:714fed014be5d092bf64b6a4f8639b4b23833b99
     volumes:
      - ./appb/config:/certificates
     environment:
      - IDP_METADATA_URL=http://citizen-consentidp/consentidp/saml2/idp/metadata.php
      - IDP_LOGIN_URL=http://localhost:8092/consentidp/saml2/idp/SSOService.php
      - CERTIFICATE=/certificates/appb.cert
      - KEY=/certificates/appb.pem
      - SP_ENTITY_ID=dev:kit:appb
      - SAML_LB_SCHEME=http
      - SAML_LB_SERVERNAME=localhost
      - SAML_LB_SERVERPORT=8084
      - APP_CONTEXT=appb
      - MONGODB=mongo
      - MONGODB_DATABASE=mongo_appb
   app-b:
     image: kitdocker.kvalitetsit.dk/kvalitetsit/serviceprovider-spviewer:714fed014be5d092bf64b6a4f8639b4b23833b99
     environment:
      - PROXY_HOST=app-b-sp-proxy
   app-b-sp-proxy:
     image: kitdocker.kvalitetsit.dk/kvalitetsit/serviceprovider-spproxy:714fed014be5d092bf64b6a4f8639b4b23833b99
     environment:
      - ENDPOINT_URL=http://app-b:8080/
      - SAML_URL=http://app-b-saml-sp:8080/
      - CONTEXT=appb
      - MONGODB=mongo
      - MONGODB_DATABASE=mongo_appb
      - CORRELATION_ID=correlation-id
     ports:
      - "8084:80"

